import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/clientes.module.css'
import NavBar from '../componentes/navBar/navBar'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Clientes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />

      <section>
        <table className={styles.table}>
          <thead>
            <tr className={styles.tableItems}>
              <th>id</th>
              <th>Nombre</th>
              <th>Apellido</th>
              <th>Email</th>
              <th>Editar</th>
              <th>Eliminar</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>asado</td>
              <td>asd</td>
              <td>qwe</td>
              <td>qwe</td>
              <td>vbn</td>
              <td>tpd</td>
            </tr>
          </tbody>
        </table>
      </section>
    </div>
  )
}
